name: Reusable Workflow

on: 
  workflow_call:
    inputs:
      who-to-greet:
        description: Who to greet
        type: string
        default: World
        required: true
    outputs:
      current-time:
        description: the current time
        value: ${{ jobs.reusable-job.outputs.current-time }}

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    outputs:
      current-time: ${{ steps.time.outputs.time }}
        
    steps:
      - run: echo Hello ${{ inputs.who-to-greet }}
      - name: set time
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT
