name: Reuse other workflow

on: 
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: 'yomama'

  use-output:
    runs-on: ubuntu-latest
    needs: call-workflow
    steps:
      - run: echo "time ${{ needs.call-workflow.current-time }}"
